input {
    kb_layout = us
}

# Keyboard backlight
bind = , keyboard_brightness_up_shortcut, exec, brightnessctl -d *::kbd_backlight set +33%
bind = , keyboard_brightness_down_shortcut, exec, brightnessctl -d *::kbd_backlight set 33%-

# Keyboard brightness
# bind = ''keyboard_brightness_up_shortcut'', exec, ~/.config/hypr/scripts/kbbacklight --inc
# bind = ''keyboard_brightness_down_shortcut'', exec, ~/.config/hypr/scripts/kbbacklight --dec

# Volume and Media Control
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMicMute, exec, pamixer --default-source -m
bind = , XF86AudioMute, exec, pamixer -t
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioPause, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Enable touchpad gestures
gesture = 3, horizontal, workspace

# Screen brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-

# Files manager
bind = SUPER, E, exec, thunar

# App launcher
bind = SUPER, F, exec, wofi --show drun

# Idle lock
bind = SUPER, L, exec, hyprlock

# Power Control
bind = SUPER, ESCAPE, exec, nwg-bar

# Clipboard
bind = SUPER, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy
bind = SUPER, V, exec, cliphist list | wofi --dmenu --pre-display-cmd "echo '%s' | cut -f 2" | cliphist decode | wl-copy

# Execs
exec-once = hypridle
exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
